from os import environ

GOOGLE_APPLICATION_CREDENTIALS=environ.get('OOGLE_APPLICATION_CREDENTIALS')
DBPGDBUSER=environ.get('DBPGDBUSER')
DBPGDBPASS=environ.get('DBPGDBPASS')
DBPGDBHOST=environ.get('DBPGDBHOST')
CLOUD_SQL_CONNECTION_NAME=environ.get('CLOUD_SQL_CONNECTION_NAME')
YOUR_DB_CONNECTION_URI=environ.get('YOUR_DB_CONNECTION_URI')
RAPIDAPIKEY=environ.get('RAPIDAPIKEY')
GCLOUD_INSTANCE=environ.get('GCLOUD_INSTANCE')
GCLOUD_CREDENTIALS= environ.get('GCLOUD_CREDENTIALS')
user=environ.get('DBPGDBUSER')
password=environ.get('DBPGDBPASS')
host=environ.get('DBPGDBHOST')
